part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const NEWS_PAGE = _Paths.NEWS_PAGE;
  static const TRENDING_SEMUA = _Paths.TRENDING_SEMUA;
  static const AREMADAY_SEMUA = _Paths.AREMADAY_SEMUA;
  static const AREMANIA_SEMUA = _Paths.AREMANIA_SEMUA;
  static const READ_BERITA_TERBARU = _Paths.READ_BERITA_TERBARU;
  static const READ_TRENDING = _Paths.READ_TRENDING;
  static const READ_AREMADAY = _Paths.READ_AREMADAY;
  static const READ_AREMANIA = _Paths.READ_AREMANIA;
  static const NGALAM_TERBARU = _Paths.NGALAM_TERBARU;
  static const NGALAM_READ_TERBARU = _Paths.NGALAM_READ_TERBARU;
  static const NGALAM_READ_DESTINASI = _Paths.NGALAM_READ_DESTINASI;
  static const NGALAM_READ_MALANGAN = _Paths.NGALAM_READ_MALANGAN;
  static const NGALAM_READ_MALANGANKULINER = _Paths.NGALAM_READ_MALANGANKULINER;
  static const NGALAM_READ_INFO_PENTING = _Paths.NGALAM_READ_INFO_PENTING;
  static const AREMA_READ_EDITORIAL = _Paths.AREMA_READ_EDITORIAL;
  static const AREMA_READ_AREMAPUTRI = _Paths.AREMA_READ_AREMAPUTRI;
  static const AREMA_READ_AREMAJUNIOR = _Paths.AREMA_READ_AREMAJUNIOR;
  static const AREMA_READ_BERITAFOTO = _Paths.AREMA_READ_BERITAFOTO;
  static const AREMA_EDITORIAL = _Paths.AREMA_EDITORIAL;
  static const AREMA_AREMAPUTRI = _Paths.AREMA_AREMAPUTRI;
  static const AREMA_AREMAJUNIOR = _Paths.AREMA_AREMAJUNIOR;
  static const AREMA_BERITAFOTO = _Paths.AREMA_BERITAFOTO;
  static const NGALAM_KULINER = _Paths.NGALAM_KULINER;
  static const NGALAM_DESTINASI = _Paths.NGALAM_DESTINASI;
  static const NGALAM_MALANGAN = _Paths.NGALAM_MALANGAN;
  static const NGALAM_INFOPENTING = _Paths.NGALAM_INFOPENTING;
  static const HALAMAN_AWAL = _Paths.HALAMAN_AWAL;
  static const FAVORITE = _Paths.FAVORITE;
  static const TICKET = _Paths.TICKET;
  static const RINCIAN_TICKET = _Paths.RINCIAN_TICKET;
  static const KATEGORI = _Paths.KATEGORI;
  static const LOGIN = _Paths.LOGIN;
  static const HALAMAN_LOGIN = _Paths.HALAMAN_LOGIN;
  static const HALAMAN_DAFTAR = _Paths.HALAMAN_DAFTAR;
  static const ABC = _Paths.ABC;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const NEWS_PAGE = '/news-page';
  static const TRENDING_SEMUA = '/trending-semua';
  static const AREMADAY_SEMUA = '/aremaday-semua';
  static const AREMANIA_SEMUA = '/aremania-semua';
  static const READ_BERITA_TERBARU = '/read-berita-terbaru';
  static const READ_TRENDING = '/read-trending';
  static const READ_AREMADAY = '/read-aremaday';
  static const READ_AREMANIA = '/read-aremania';
  static const NGALAM_TERBARU = '/ngalam-terbaru';
  static const NGALAM_READ_TERBARU = '/ngalam-read-terbaru';
  static const NGALAM_READ_DESTINASI = '/ngalam-read-destinasi';
  static const NGALAM_READ_MALANGAN = '/ngalam-read-malangan';
  static const NGALAM_READ_MALANGANKULINER = '/ngalam-read-malangankuliner';
  static const NGALAM_READ_INFO_PENTING = '/ngalam-read-info-penting';
  static const AREMA_READ_EDITORIAL = '/arema-read-editorial';
  static const AREMA_READ_AREMAPUTRI = '/arema-read-aremaputri';
  static const AREMA_READ_AREMAJUNIOR = '/arema-read-aremajunior';
  static const AREMA_READ_BERITAFOTO = '/arema-read-beritafoto';
  static const AREMA_EDITORIAL = '/arema-editorial';
  static const AREMA_AREMAPUTRI = '/arema-aremaputri';
  static const AREMA_AREMAJUNIOR = '/arema-aremajunior';
  static const AREMA_BERITAFOTO = '/arema-beritafoto';
  static const NGALAM_KULINER = '/ngalam-kuliner';
  static const NGALAM_DESTINASI = '/ngalam-destinasi';
  static const NGALAM_MALANGAN = '/ngalam-malangan';
  static const NGALAM_INFOPENTING = '/ngalam-infopenting';
  static const HALAMAN_AWAL = '/halaman-awal';
  static const FAVORITE = '/favorite';
  static const TICKET = '/ticket';
  static const RINCIAN_TICKET = '/rincian-ticket';
  static const KATEGORI = '/kategori';
  static const LOGIN = '/login';
  static const HALAMAN_LOGIN = '/halaman-login';
  static const HALAMAN_DAFTAR = '/halaman-daftar';
  static const ABC = '/abc';
}
